trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.3.5'
  AZURE_SUBSCRIPTION: '71b5939b-c815-41f4-a455-8323e846ebea'

stages:
  - stage: Terraform_Apply
    jobs:
      - job: Apply_Terraform
        steps:
          - task: UseTerraform@0
            inputs:
              version: $(TF_VERSION)
          - script: |
              terraform init
              terraform plan
              terraform apply -auto-approve
            displayName: 'Terraform Apply'
