trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.6.0'
  serviceConnection: 'Terraform-SPN'

stages:
  - stage: Terraform
    jobs:
      - job: Deploy
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(terraformVersion)

          - task: TerraformCLI@0
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)'

          - task: TerraformCLI@0
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              environmentServiceName: '$(serviceConnection)'

          - task: TerraformCLI@0
            displayName: 'Terraform Apply'
            condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              environmentServiceName: '$(serviceConnection)'
              commandOptions: '-auto-approve'
